#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fiduswriter"
name = "Fidus Writer"
description.en = "an online collaborative editor for academics"
description.fr = "un éditeur collaboratif en ligne pour les universitaires"

version = "4.0.18~ynh1"

maintainers = ["DeMiro5001"]

[upstream]
license = "GPL-3.0-only"
website = "https://fiduswriter.org/"
demo = "https://www.fiduswriter.com"
admindoc = "https://github.com/fiduswriter/fiduswriter/tree/develop/docs/installation"
userdoc = "https://github.com/fiduswriter/fiduswriter/blob/develop/docs/README.md"
code = "https://github.com/fiduswriter/fiduswriter"

fund = "https://www.fiduswriter.org/donate/"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Admin password."
    help.fr = "Mot de passe de l'administrateur."
    type = "password"

    [install.is_free]
    ask.en = "This determines whether there is a star labeled **Free** on the login page?"
    type = "boolean"
    default = false

    [install.registration_open]
    ask.en = "Allow new user registration"
    type = "boolean"
    default = false

    [install.password_login]
    ask.en = "Enable password-based login"
    type = "boolean"
    default = true

    [install.socialaccount_open]
    ask.en = "Enable social account login"
    type = "boolean"
    default = false
    
[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/fiduswriter/fiduswriter/archive/refs/tags/v4.0.18.tar.gz"
    sha256 = "7d666c7698bea05b892259c528e36e4c472987ae5234ccf86a6d0819ad50ad5e"
    in_subdir = true

    autoupdate.strategy = "latest_github_tag"

    [resources.sources.uv]
    amd64.url = "https://github.com/astral-sh/uv/releases/download/0.10.4/uv-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "6b52a47358deea1c5e173278bf46b2b489747a59ae31f2a4362ed5c6c1c269f7"
    arm64.url = "https://github.com/astral-sh/uv/releases/download/0.10.4/uv-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "c84a6e6405715caa6e2f5ef8e5f29a5d0bc558a954e9f1b5c082b9d4708c222e"
    armhf.url = "https://github.com/astral-sh/uv/releases/download/0.10.4/uv-armv7-unknown-linux-gnueabihf.tar.gz"
    armhf.sha256 = "d1824ed14f3ad0e7cb7835b46bc0299859cd8141d039a66274a135ca9797bf9c"
    i386.url = "https://github.com/astral-sh/uv/releases/download/0.10.4/uv-i686-unknown-linux-gnu.tar.gz"
    i386.sha256 = "79821b1d6c035aa8dc32a45d41551a4f010b8e357c98df48c95c5cb5ec18a743"
    
    in_subdir = true
    
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/astral-sh/uv"
    autoupdate.asset.amd64 = "^uv-x86_64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.arm64 = "^uv-aarch64-unknown-linux-gnu.tar.gz$"
    autoupdate.asset.armhf = "^uv-armv7-unknown-linux-gnueabihf.tar.gz$"
    autoupdate.asset.i386 = "^uv-i686-unknown-linux-gnu.tar.gz$"

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]
    subdirs = ['media']

    [resources.permissions]
    main.url = "/"
    admin.url = "/admin"
    admin.allowed = "admins"
    admin.show_tile = false

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3-pip, python3-venv, python3-dev, redis-server, libjpeg-dev, zlib1g-dev, gettext, libpq-dev, libldap2-dev, libsasl2-dev, rsync"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
