#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

secret_key=$(ynh_string_random --length=64)
ynh_app_setting_set --key=secret_key --value=$secret_key

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
ynh_app_setting_set --key=admin_mail --value=$admin_mail

timezone="$(timedatectl show --value --property=Timezone)"
ynh_app_setting_set --key=timezone --value=$timezone

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app=$app --key=redis_db --value=$redis_db

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/.uv" --source_id="uv"
chmod +x "$install_dir/.uv/uv"
chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="../conf/configuration.py" --destination="$install_dir/fiduswriter/configuration.py"

chmod 400 "$install_dir/fiduswriter/configuration.py"
chown "$app:$app" "$install_dir/fiduswriter/configuration.py"

ynh_script_progression "Preparing UV..."
    export PATH="$install_dir/.uv:$PATH"
    export UV_PYTHON_INSTALL_DIR="$install_dir/.python_runtime"
    export UV_CACHE_DIR="$install_dir/.uv_cache"
    ynh_exec_as_app echo "PATH=$install_dir/bin:\$PATH" >> $install_dir/.bashrc 
    echo "UV_PYTHON_INSTALL_DIR=$install_dir/.python_runtime" >> $install_dir/.bashrc 
    echo "UV_CACHE_DIR=$install_dir/.uv_cache" >> $install_dir/.bashrc

ynh_script_progression "Installing $app's dependencies..."

pushd $install_dir
    ynh_exec_as_app uv venv "$install_dir/.venv" --python 3.12
    echo "source $install_dir/.venv/bin/activate" >> $install_dir/.bashrc
    source $install_dir/.venv/bin/activate
    ynh_exec_as_app uv pip install --upgrade pip setuptools wheel gunicorn uvicorn psycopg django_redis django-auth-ldap
    cd fiduswriter
    ynh_exec_as_app uv pip install -r requirements.txt
    ynh_exec_as_app uv pip install -r postgresql-requirements.txt
    mkdir static-libs
    mkdir static-transpile
    ynh_exec_as_app python manage.py migrate
    ynh_exec_as_app python manage.py transpile
    ynh_exec_as_app python manage.py collectstatic --noinput
    ynh_exec_as_app DJANGO_SUPERUSER_USERNAME=$admin DJANGO_SUPERUSER_EMAIL=$admin_mail DJANGO_SUPERUSER_PASSWORD=$password python manage.py createsuperuser --noinput
    ynh_exec_as_app python manage.py setup
    deactivate
popd

chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Gunicorn for $app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
