#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

secret_key=$(ynh_string_random --length=64)
ynh_app_setting_set --key=secret_key --value=$secret_key

admin_mail=$(ynh_user_get_info --username=$admin --key=mail)
ynh_app_setting_set --key=admin_mail --value=$admin_mail

timezone="$(timedatectl show --value --property=Timezone)"
ynh_app_setting_set --key=timezone --value=$timezone

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --app=$app --key=redis_db --value=$redis_db

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="../conf/configuration.py" --destination="$install_dir/fiduswriter/configuration.py"

chmod 400 "$install_dir/fiduswriter/configuration.py"
chown "$app:$app" "$install_dir/fiduswriter/configuration.py"

ynh_script_progression "Installing $app's dependencies..."

pushd $install_dir
    python -m venv venv
    source venv/bin/activate
    echo "source $install_dir/venv/bin/activate" >> $install_dir/.bashrc
    cd fiduswriter
    pip install -r requirements.txt
    pip install -r postgresql-requirements.txt
    pip install gunicorn gevent
    python manage.py migrate
    python manage.py transpile --noinput
    python manage.py collectstatic --noinput
    #DJANGO_SUPERUSER_USERNAME=$admin DJANGO_SUPERUSER_EMAIL=$admin_mail DJANGO_SUPERUSER_PASSWORD=$password python manage.py createsuperuser --noinput
    pip install django-auth-ldap
    deactivate
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Gunicorn for $app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
