#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=php_upload_max_filesize --value=50M
ynh_app_setting_set_default --key=php_post_max_size --value=50M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".venv"
chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="../conf/configuration.py" --destination="$install_dir/fiduswriter/configuration.py"

chmod 400 "$install_dir/fiduswriter/configuration.py"
chown "$app:$app" "$install_dir/fiduswriter/configuration.py"

ynh_script_progression "Upgrading uv..."

    ynh_setup_source --dest_dir="$install_dir/.uv" --source_id="uv"
    chmod +x "$install_dir/.uv/uv"
    export PATH="$install_dir/.uv:$PATH"
    export UV_PYTHON_INSTALL_DIR="$install_dir/.python_runtime"
    export UV_CACHE_DIR="$install_dir/.uv_cache"

ynh_script_progression "Updating $app's dependencies..."

pushd $install_dir
    source .venv/bin/activate
    cd fiduswriter
    ynh_hide_warnings uv pip install -r requirements.txt
    ynh_hide_warnings uv pip install -r postgresql-requirements.txt
    ynh_hide_warnings uv pip install -U pip setuptools wheel gunicorn uvicorn psycopg django_redis django-auth-ldap
    python manage.py migrate
    python manage.py transpile
    python manage.py collectstatic --noinput
    deactivate
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Gunicorn for $app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
